# H2 database for now
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

# JPA dialect
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

# Session timeout
server:
  servlet:
    session:
      timeout: 15m

session:
  store-type: none
